# -*- coding: utf-8 -*-
"""Text_Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TUoebkIzZP-hH0EQ5g8oVlFt4tw2i7vd
"""

!pip install easyocr[gpu]

!pip install easyocr

import cv2
import matplotlib.pyplot as plt
import easyocr
from google.colab import drive

drive.mount('/content/drive')

images_dir = '/content/drive/MyDrive/text_detection/'

image_file = 'test_2.jpg'

reader = easyocr.Reader(['en'],gpu=True)

threshould=0.50
img_path = images_dir + image_file
img = cv2.imread(img_path)
desired_width = 800
desired_height = 600
img = cv2.resize(img, (desired_width, desired_height))
text_= reader.readtext(img)

print(f"Detected text in {image_file}:")
for t in text_:

    bbox,text,score=t
    x1, y1 = int(bbox[0][0]), int(bbox[0][1])
    x2, y2 = int(bbox[2][0]), int(bbox[2][1])

    if score>threshould:
        cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 34), 5)
        cv2.putText(img, text, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX,1, (100, 23, 255),2)





plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.show()

